services:
  db:
    ports: !reset []

  content-import:
    environment:
      DATABASE_PUSH: 'false'

  app:
    ports: !override
      - '3008:3000'
    environment:
      NEXT_PUBLIC_SERVER_URL: https://hagencreative.tw
      NODE_ENV: production
    volumes:
      - ./content/media:/app/media
